In [1]:
import pandas as pd
import numpy as np
import math
import missingno as mn
import matplotlib.pyplot as plt
import seaborn as sn
from geopy.geocoders import Nominatim

In [40]:
#now try and get latitude and longitude of the cities

geolocator = Nominatim(user_agent= "GoogleV3")
testvar = geolocator.geocode('bridgend')
testvar.latitude
testvar.longitude

-3.56409092910681

In [70]:
geolocator.geocode('w42qx')

In [71]:
#ok lets say theres two entries
d= {}
geolocator = Nominatim(user_agent= "GoogleV3")
numentries = int(input("how many addresses you got fool?"))
z = 1
while z <= numentries:
    #user_input = input
    d["user_input{0}".format(z)] = input("What's your address yo? ")
    #type(name)
    #d["user_input{0}".format(z)]= "London"
    d["user_input_geocode{0}".format(z)]  = geolocator.geocode(d["user_input{0}".format(z)])
    try:
        d["user_input_latitude{0}".format(z)] = d["user_input_geocode{0}".format(z)].latitude
        d["user_input_longitude{0}".format(z)] = d["user_input_geocode{0}".format(z)].longitude
    except:
        print("this failed! The address must have been whack")
    z += 1

how many addresses you got fool?2
What's your address yo? chiswick, london
What's your address yo? canary wharf,london

In [60]:
d["user_input_latitude{0}".format(2)]

51.55696625

In [18]:
#read in the pubs dataset already processed with distance to their nearest tube line attached
#easiest thing is probably to start adding total travel time to nearest node point of a different line
#again can cover that later, for now just take the closest one
#orrrr just treat them as independant pubs and double the length of your data, it wouldn't add much processing time
%store -r pubswithdist
#read in the already calculated tube network travel time data set
%store -r data_tubetravel

#pubswithdist = pd.read_csv('C:\\Users\\George\\Downloads\\MITM\\pubswithdist.csv',index_col=0)
#data_tubetravel = pd.read_csv('C:\\Users\\George\\Downloads\\MITM\\data_tubetravel.csv',index_col=0)

data_stations = pd.read_csv("C:\\Users\\George\\Downloads\\MITM\\stations_csv.sv.csv")
#now grab the all important travel times
data_travel = pd.read_csv("C:\\Users\\George\\Downloads\\MITM\\travel_times.csv")

In [19]:
#need to assign every pub a nearest tube
#need to define a function for distance between coordinates
#use the haversine formula
#need the angle in radians

def coords_to_distance(x1,x2,y1,y2):
    x1 = x1 * math.pi / 180
    x2 = x2 * math.pi / 180
    y1 = y1 * math.pi / 180
    y2 = y2 * math.pi / 180
    dlat = x2 - x1
    dlon = y2 - y1
    a = (math.pow(math.sin(dlat/2),2)) + math.cos(x1) * math.cos(x2) * (math.pow(math.sin(dlon/2),2))
    c = 2 * math.atan2(math.sqrt(a),math.sqrt(1-a))
    d = c * 6373
    #this is in km
    return d

In [20]:
#need to calculate nearest station using the above, then get time from that to all pubs
#then probably get the second nearest station as well and repeat
#and also do a rough and ready walking calculation
#this could be improved, could use a machine learning algorithm to learn faster and slower bits of london walking
#come back to that later

In [21]:
def find_second_station(previous_station):
    alreadycheckedlines= []
    for line in data_travel[data_travel['station1'] == previous_station].iterrows():
        #print(line)
        alreadycheckedlines.append(line[1]['line'])
        datatravel_temp = data_travel[~data_travel['line'].isin(alreadycheckedlines)]
        data_filtered = data_stations[data_stations['id'].isin(datatravel_temp['station1'])]
    return data_filtered

In [25]:
#need this to be self contained, and output an identifiable dataset ready for further processing
def distance_to_pubs(input_lat,input_long,user_num,data_stations):
    min_distance = 1000
    closest_tube_id = []
    closest_tube = []
    for tube in data_stations.itertuples():
        #get distance between input coords and all tubes
        current_dist = coords_to_distance(getattr(tube,'latitude'),input_lat,getattr(tube,'longitude'),input_long)
        if current_dist < min_distance:
            min_distance = current_dist
            closest_tube_id = getattr(tube,'id')
            #closest_line = getattr(line, '')
            #this will return the closest tube station id to the input coords
            #could potentially be optimised further but not worth it because of how quick it currently is
            
    #this loop returns the closest tube station to the input coords
    #then the below works out the travel time to all the things from that
    #data tubetravel contains travel time from each tube station to every other tube station
    #so just filter to the nearest tube station and check time to the rest of the network
    #need to check each line as well
    
    q= 1
    person_travel = []
    tube_id = []
    tube_results = []
    for line in data_tubetravel[data_tubetravel['id'] == closest_tube_id]['travel_times']:
        while q < len(data_stations):
            person_travel.append(line[q]['time']) 
            tube_id.append(q)
            q += 1

    #the above returns the travel time to all stations from the nearest station
    user_num = str(user_num)    
    person_travel = pd.DataFrame(person_travel)
    tube_id = pd.DataFrame(tube_id)
    individ_tube = pd.merge(tube_id,person_travel,left_index = True, right_index = True)
    individ_tube.columns = ['tube_id','travel_time_to_tube'+user_num]
    
    
    full_travel = pd.merge(pubs_with_dist_filt,individ_tube, how = 'left',left_on = '0_y',right_on = 'tube_id')
    min_distance_time = min_distance / 0.084
    full_travel['total time' + user_num] = full_travel['traveltime_totube_pub'] + full_travel['travel_time_to_tube'+str(user_num)] + min_distance_time
    return full_travel,closest_tube_id

In [26]:
#troubleshoot the zeros

In [61]:
#could be worth filtering pubs with dist to only a couple of columns so that it's neater?
pubs_with_dist_filt = pubswithdist[['0_y','index','traveltime_totube_pub']]
numpeeps = 2
i = 1
while i <= numpeeps:
    full_travel_i_1, i_closest_tube_id = distance_to_pubs(d["user_input_latitude{0}".format(i)],d["user_input_longitude{0}".format(i)],i,data_stations)
    full_travel_i_2, i_second_closest_tube = distance_to_pubs(d["user_input_latitude{0}".format(i)],d["user_input_longitude{0}".format(i)],i,find_second_station(i_closest_tube_id))
    full_travel_i = pd.merge(full_travel_i_1,full_travel_i_2, left_index=True,right_index=True)
    #full_travel_i['True_shortest' + str(i)] = min(full_travel_i['total time' + str(i) + '_x'], full_travel_i['total time' + str(i) + '_y'])
    full_travel_i['true_shortest' + str(i)] = full_travel_i[['total time' + str(i) + '_x', 'total time' + str(i) + '_y']].min(axis=1)
    full_travel_i_final = full_travel_i[['true_shortest' + str(i)]]
    if i > 1:
        full_current = pd.merge(full_travel_i_final,full_current,left_index=True,right_index=True)
    else:
        full_current = full_travel_i_final
    i += 1
#test_fulltravel,test_closest_tube_id = distance_to_pubs(51.5020275,-0.0267862,2,data_stations)
#this works fine, worth in your loop goingn twice for each person and checking the other nearest tube
#then combine those datasets, take only the shortest travel time to each pub and move on
#ok so once that works what needs to happen?

In [28]:
#just need the minimum, then merge, then filter and done!
#numpeeps is the number of columns
cols_to_use = ['true_shortest' + str(i+1) for i in range(numpeeps)]
#full_current['Total'] = full_current.loc[:, cols_to_use].sum(axis=1)
full_current['Total'] = full_current[cols_to_use].sum(axis =1 )
full_current = pd.merge(full_current,pubswithdist,left_index= True,right_index=True)
full_current = full_current[full_current['Total'] != 0]

In [29]:
finalfinal = full_current.sort_values('Total')
#full_current
#full_current[full_current.index == 1767] 
#full_current[full_current['Total'] == 0]

In [30]:
#i = 1
#while i < numpeeps:
#    j = i + 1
#    full_travel_i_final = pd.merge(full_travel_i_final,full_travel_j_final,left_index=True,right_index = True)
#    i += 1
#once this happens you still need to choose the minimum five values then output the pubs

In [31]:
#need a sum all columns function
#a couple of pubs are missing their coords, ignore for now I guess
#mn.matrix(pubswithdist)

In [32]:
#then finally...
#select the minimum five
#pd.merge(min_five,pubswithist,left_index=True,right_index=True, how= 'inner')

In [33]:
#full_travel_i_final.head(10)

In [34]:
finalfinal

,true_shortest2,true_shortest1,Total,index,0_x,1,2,3,4,5,6,7,8,latitude,longitude,0_y,0,traveltime_totube,traveltime_totube_pub
3314,7.386873,7.386873,14.773745,12600,140031,All Bar One,"""All Bar One, 42 Mackenzie Walk, London""",E14 5EH,537481,180236.0,51.504335,-0.020542,Tower Hamlets,51.504335,-0.020542,42,0.088627,1.055087,1.055087
3393,7.386873,7.386873,14.773745,12679,141942,Slug and Lettuce,"""30a South Colonnade, London""",E14 5EZ,537481,180236.0,51.504335,-0.020542,Tower Hamlets,51.504335,-0.020542,42,0.088627,1.055087,1.055087
3376,7.558988,7.558988,15.117976,12662,141471,Nicolas,"""Unit RP480, 1 Canada Square, London""",E14 5AX,537557,180305.0,51.504938,-0.019434,Tower Hamlets,51.504938,-0.019434,42,0.103085,1.227202,1.227202
3426,7.575081,7.575081,15.150163,12712,142252,The Henry Addington,"""Henry Addington, 22-28 Mackenzie Walk, London""",E14 4PH,537373,180253.0,51.504523,-0.02209,Tower Hamlets,51.504523,-0.022090,42,0.104437,1.243296,1.243296
3455,7.612257,7.612257,15.224515,12741,142340,The Tea Merchant,"""25-27 Fishermans Walk, London""",E14 4DH,537394,180409.0,51.505919,-0.021726,Tower Hamlets,51.505919,-0.021726,42,0.107560,1.280472,1.280472
3415,7.613817,7.613817,15.227634,12701,142226,The Fine Line,"""29-30 Fishermans Walk, London""",E14 4DH,537394,180409.0,51.50592,-0.021727,Tower Hamlets,51.505920,-0.021727,42,0.107691,1.282032,1.282032
3339,7.613817,7.613817,15.227634,12625,140591,Davys At Canary Wharf,"""31-35 Fishermans Walk, London""",E14 4DH,537394,180409.0,51.50592,-0.021727,Tower Hamlets,51.505920,-0.021727,42,0.107691,1.282032,1.282032
3444,7.613817,7.613817,15.227634,12730,142300,The Pagination,"""9 Cabot Square, London""",E14 4EB,537394,180409.0,51.50592,-0.021727,Tower Hamlets,51.505920,-0.021727,42,0.107691,1.282032,1.282032
3452,9.534042,9.534042,19.068083,12738,142332,The Sipping Room,"""16 Hertsmere Road, London""",E14 4EF,537418,180544.0,51.507118,-0.021329,Tower Hamlets,51.507118,-0.021329,291,0.072438,0.862359,0.862359
3417,10.664390,10.664390,21.328781,12703,142231,The George,"""114-114a Glengall Grove, London""",E14 3ND,538101,179294.0,51.495719,-0.011983,Tower Hamlets,51.495719,-0.011983,61,0.167387,1.992708,1.992708
3378,11.592368,11.592368,23.184737,12664,141583,Pepper Saint Ontiod,"""21 Pepper Street, London""",E14 9RP,537691,179329.0,51.496142,-0.017871,Tower Hamlets,51.496142,-0.017871,61,0.245338,2.920686,2.920686
3428,11.728108,11.728108,23.456216,12714,142271,The Ledger Building,"""Ledger Building, 4 Hertsmere Road, London""",E14 4AL,537241,180599.0,51.507655,-0.023856,Tower Hamlets,51.507655,-0.023856,291,0.256740,3.056426,3.056426
3461,12.999069,12.999069,25.998139,12747,142376,Tooke Arms,"""Tooke Arms Public House, 165 Westferry Road, ...",E14 8NH,537153,179533.0,51.498097,-0.025537,Tower Hamlets,51.498097,-0.025537,237,0.531501,6.327387,6.327387
3470,13.002284,13.002284,26.004569,12756,142512,White Swan,"""White Swan, 556 Commercial Road, London""",E14 7JD,536092,181122.0,51.512642,-0.0402,Tower Hamlets,51.512642,-0.040200,155,0.056322,0.670499,0.670499
3407,13.002284,13.002284,26.004569,12693,142207,The Craft Beer Co Limehouse,"""576-578 Commercial Road, London""",E14 7JD,536092,181122.0,51.512642,-0.0402,Tower Hamlets,51.512642,-0.040200,155,0.056322,0.670499,0.670499
3215,13.397430,13.397430,26.794859,12501,138782,The gregorian,"""The Gregorian, 94a-96, Jamaica Road, London""",SE16 4SQ,534334,179406.0,51.497641,-0.066171,Southwark,51.497641,-0.066171,23,0.173514,2.065644,2.065644
3410,13.738135,13.738135,27.476271,12696,142211,The Crown,"""The Crown Public House, 667 Commercial Road, ...",E14 7LW,536233,181151.0,51.512868,-0.038158,Tower Hamlets,51.512868,-0.038158,155,0.118133,1.406350,1.406350
3464,14.018667,14.018667,28.037334,12750,142428,Urban Bar,"""27 Three Colt Street, London""",E14 8HH,536820,180981.0,51.511199,-0.02977,Tower Hamlets,51.511199,-0.029770,283,0.281147,3.346985,3.346985
3384,14.266420,14.266420,28.532839,12670,141718,Queens Head,"""Queens Head Public House, 8 Flamborough Stree...",E14 7LS,536181,181241.0,51.513689,-0.038872,Tower Hamlets,51.513689,-0.038872,155,0.162509,1.934634,1.934634
3357,14.390910,14.390910,28.781820,12643,140925,Hope & Anchor,"""14 Newby Place, London""",E14 0EY,538066,180805.0,51.509305,-0.011896,Tower Hamlets,51.509305,-0.011896,4,0.172966,2.059124,2.059124
3441,14.492473,14.492473,28.984947,12727,142295,The Old Ship,"""The Old Ship Public House, 17 Barnes Street, ...",E14 7NW,536110,181265.0,51.513922,-0.039886,Tower Hamlets,51.513922,-0.039886,155,0.181498,2.160688,2.160688
3414,14.507898,14.507898,29.015796,12700,142225,The Ferry House,"""Ferry House Public House, 26 Ferry Street, Lo...",E14 3DT,538104,178321.0,51.486983,-0.012319,Tower Hamlets,51.486983,-0.012319,135,0.154242,1.836216,1.836216
3380,14.508608,14.508608,29.017216,12666,141652,Poplar Blackwall & District Rowing Bar,"""Ferry Street, London""",E14 3DT,538104,178321.0,51.486984,-0.01232,Tower Hamlets,51.486984,-0.012320,135,0.154302,1.836926,1.836926
3434,14.585820,14.585820,29.171639,12720,142281,The Manor Arms,"""150 East India Dock Road, London""",E14 0BP,537796,180973.0,51.51089,-0.015718,Tower Hamlets,51.510890,-0.015718,4,0.189339,2.254034,2.254034
3432,14.606394,14.606394,29.212788,12718,142279,The Lord Nelson,"""Lord Nelson Public House, 1-1a Manchester Roa...",E14 3BD,538100,178380.0,51.487506,-0.012354,Tower Hamlets,51.487506,-0.012354,135,0.162516,1.934712,1.934712
3422,14.629365,14.629365,29.258729,12708,142242,The Greenwich Pensioner,"""The Greenwich Pensioner, 28 Bazely Street, Lo...",E14 0ES,538150,180856.0,51.509752,-0.010665,Tower Hamlets,51.509752,-0.010665,4,0.192997,2.297579,2.297579
3394,14.758043,14.758043,29.516086,12680,142015,Star of the East,"""805a Commercial Road, London""",E14 7HG,536865,181109.0,51.512338,-0.029073,Tower Hamlets,51.512338,-0.029073,283,0.343254,4.086361,4.086361
3472,14.925690,14.925690,29.851379,12758,142518,Widows Son,"""75 Devons Road, London""",E3 3PJ,537602,182234.0,51.522268,-0.018019,Tower Hamlets,51.522268,-0.018019,70,0.049888,0.593904,0.593904
3451,15.098159,15.098159,30.196319,12737,142331,The Ship,"""290 Westferry Road, London""",E14 3AG,537662,178430.0,51.488071,-0.018639,Tower Hamlets,51.488071,-0.018639,171,0.371824,4.426477,4.426477
3175,15.116189,15.116189,30.232378,12461,138500,St james of bermondsey,"""72, St Jamess Road, London""",SE16 4QZ,534347,179164.0,51.495455,-0.066077,Southwark,51.495455,-0.066077,23,0.317890,3.784403,3.784403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,178.667909,178.667909,357.335817,9365,92206,Change Of Horses,"""87 High Street, Farnborough, Orpington""",BR6 7BB,544058,164303.0,51.359538,0.067682,Bromley,51.359538,0.067682,152,13.103683,155.996226,155.996226
437,179.851257,179.851257,359.702514,9386,92527,Farnborough Sports Club,"""Farrow Fields, High Street, Farnborough, Orpi...",BR6 7BA,544216,164273.0,51.359229,0.069937,Bromley,51.359229,0.069937,152,13.203084,157.179575,157.179575
546,179.851257,179.851257,359.702514,9495,93893,The Woodman,"""50 High Street, Farnborough, Orpington""",BR6 7BA,544216,164273.0,51.359229,0.069937,Bromley,51.359229,0.069937,152,13.203084,157.179575,157.179575
408,180.228990,180.228990,360.457981,9357,92109,Bromley Indoor Bowls Centre,"""Bodmin Close, Orpington""",BR5 4LX,547105,166288.0,51.376585,0.112234,Bromley,51.376585,0.112234,152,13.234814,157.557308,157.557308
1105,180.612070,180.612070,361.224140,10054,101216,The Village Club,"""151 Addington Road, South Croydon""",CR2 8LH,535130,162387.0,51.344511,-0.061199,Croydon,51.344511,-0.061199,169,11.279544,134.280284,134.280284
463,181.132552,181.132552,362.265104,9412,93144,Naturist Foundation - Tea Pot Cafe,"""Brockenhurst, Sheepcote Lane, Orpington""",BR5 4ET,548735,167991.0,51.391472,0.136349,Bromley,51.391472,0.136349,152,13.310713,158.460870,158.460870
3735,182.580519,182.580519,365.161037,26213,271679,Netherne Community Amateur Sports Club,"""Woodplace Lane, Hooley, Surrey""",CR5 1NB,529495,157775.0,51.304374,-0.143729,Croydon,51.304374,-0.143729,169,11.444894,136.248733,136.248733
518,186.899948,186.899948,373.799895,9467,93804,The Buff,"""Pinewood Drive, Orpington""",BR6 9NL,545380,164260.0,51.358806,0.086638,Bromley,51.358806,0.086638,152,13.795174,164.228265,164.228265
555,188.274825,188.274825,376.549650,9504,94008,Warbank Social Club,"""Warbank Crescent, Croydon""",CR0 0AY,539246,162091.0,51.34086,-0.002251,Croydon,51.340860,-0.002251,152,13.910664,165.603143,165.603143
526,189.102579,189.102579,378.205157,9475,93818,The Crown Inn,"""Leaves Green Road, Keston""",BR2 6DQ,541598,162429.0,51.343307,0.031628,Bromley,51.343307,0.031628,152,13.980195,166.430896,166.430896
558,194.610726,194.610726,389.221452,9507,94015,Westcombe Park Rugby Football Club - Club Cate...,"""Orpington Sports Club, Goddington Lane, Orpin...",BR6 9SX,547317,164863.0,51.363726,0.114687,Bromley,51.363726,0.114687,152,14.442880,171.939044,171.939044
487,194.681506,194.681506,389.363011,9436,93385,Queens Head,"""The Queens Head, 73 High Street, Green Street...",BR6 6BQ,545577,163612.0,51.352942,0.089201,Bromley,51.352942,0.089201,152,14.448825,172.009823,172.009823
496,196.688276,196.688276,393.376552,9445,93460,Royal Oak Beefeater,"""Royal Oak, 72 High Street, Green Street Green...",BR6 6BJ,545602,163430.0,51.3513,0.089485,Bromley,51.351300,0.089485,152,14.617394,174.016594,174.016594
418,197.287298,197.287298,394.574596,9367,92221,Chelsfield Lakes Golf Centre,"""Court Road, Orpington""",BR6 9BX,547397,164637.0,51.361675,0.115742,Bromley,51.361675,0.115742,152,14.667712,174.615616,174.615616
521,197.890291,197.890291,395.780582,9470,93811,The Chelsfield,"""1 Windsor Drive, Orpington""",BR6 6EY,546687,164024.0,51.356359,0.105285,Bromley,51.356359,0.105285,152,14.718363,175.218609,175.218609
535,199.151561,199.151561,398.303122,9484,93851,The Kings Arms,"""Leaves Green Road, Keston""",BR2 6DU,541402,161511.0,51.335107,0.028452,Bromley,51.335107,0.028452,152,14.824310,176.479879,176.479879
448,199.186827,199.186827,398.373654,9397,92699,High Elms Golf Club,"""High Elms Golf Course Club House, High Elms R...",BR6 7JL,543921,162333.0,51.341871,0.064919,Bromley,51.341871,0.064919,152,14.827272,176.515145,176.515145
486,202.534571,202.534571,405.069143,9435,93384,Queens Head,"""25 High Street, Downe, Orpington""",BR6 7US,543165,161733.0,51.33667,0.053832,Bromley,51.336670,0.053832,152,15.108483,179.862889,179.862889
441,203.069785,203.069785,406.139569,9390,92586,George And Dragon,"""26 High Street, Downe, Orpington""",BR6 7UT,543156,161682.0,51.336214,0.053682,Bromley,51.336214,0.053682,152,15.153441,180.398102,180.398102
556,203.118817,203.118817,406.237635,9505,94013,West Kent Golf Club - Executive Catering,"""West Kent Golf Club, Milking Lane, Downe, Orp...",BR6 7LD,542257,161389.0,51.333797,0.040668,Bromley,51.333797,0.040668,152,15.157559,180.447135,180.447135
439,208.110268,208.110268,416.220536,9388,92552,Five Bells,"""Church Road, Chelsfield, Orpington""",BR6 7RE,548233,164150.0,51.35709,0.127539,Bromley,51.357090,0.127539,152,15.576841,185.438586,185.438586
413,218.781381,218.781381,437.562762,9362,92132,Bulls Head,"""Rushmore Hill, Orpington""",BR6 7NQ,547188,162236.0,51.340155,0.111736,Bromley,51.340155,0.111736,152,16.473215,196.109699,196.109699
516,220.265124,220.265124,440.530249,9465,93798,The Bo Peep,"""The Bo-Peep, Hewitts Road, Orpington""",BR6 7QL,548946,163415.0,51.3503,0.137464,Bromley,51.350300,0.137464,152,16.597849,197.593442,197.593442
539,229.811579,229.811579,459.623159,9488,93868,The Old Jail,"""Jail Lane, Biggin Hill""",TN16 3AX,543125,159305.0,51.314871,0.052284,Bromley,51.314871,0.052284,152,17.399751,207.139897,207.139897
419,229.811579,229.811579,459.623159,9368,92224,Cherry Lodge Golf Club - Four Seasons Cuisine,"""Cherry Lodge Golf Club, Jail Lane, Biggin Hill""",TN16 3AX,543125,159305.0,51.314871,0.052284,Bromley,51.314871,0.052284,152,17.399751,207.139897,207.139897
529,229.985913,229.985913,459.971825,9478,93827,The Flying Machine,"""Kings Road, Biggin Hill""",TN16 3XY,541318,158845.0,51.31118,0.026191,Bromley,51.311180,0.026191,152,17.414395,207.314230,207.314230
397,230.798935,230.798935,461.597869,9346,92023,Black Horse,"""The Black Horse, 123 Main Road, Biggin Hill""",TN16 3AY,541885,158893.0,51.31147,0.034339,Bromley,51.311470,0.034339,152,17.482689,208.127252,208.127252
400,231.602893,231.602893,463.205786,9349,92028,Blacksmiths Arms,"""Cudham Lane South, Cudham, Sevenoaks""",TN14 7QB,544631,159677.0,51.317833,0.074029,Bromley,51.317833,0.074029,152,17.550222,208.931211,208.931211
395,232.586895,232.586895,465.173791,9344,92012,Biggin Hill Social And Sports Club,"""138 - 140 Main Road, Biggin Hill""",TN16 3BA,541978,158759.0,51.310252,0.03562,Bromley,51.310252,0.035620,152,17.632878,209.915213,209.915213
511,246.550830,246.550830,493.101660,9460,93788,The Aperfield Inn,"""311 Main Road, Biggin Hill""",TN16 2HN,543143,157846.0,51.301747,0.051957,Bromley,51.301747,0.051957,152,18.805848,223.879148,223.879148

In [35]:
#pubswithdist
finalfinal = full_current.sort_values('Total')
finalfinal_top = finalfinal.head(10)
finalfinal_top = finalfinal_top[['Total',2,8]]

In [36]:
#pubswithdist
finalfinal_top

,Total,2,8
3314,14.773745,"""All Bar One, 42 Mackenzie Walk, London""",Tower Hamlets
3393,14.773745,"""30a South Colonnade, London""",Tower Hamlets
3376,15.117976,"""Unit RP480, 1 Canada Square, London""",Tower Hamlets
3426,15.150163,"""Henry Addington, 22-28 Mackenzie Walk, London""",Tower Hamlets
3455,15.224515,"""25-27 Fishermans Walk, London""",Tower Hamlets
3415,15.227634,"""29-30 Fishermans Walk, London""",Tower Hamlets
3339,15.227634,"""31-35 Fishermans Walk, London""",Tower Hamlets
3444,15.227634,"""9 Cabot Square, London""",Tower Hamlets
3452,19.068083,"""16 Hertsmere Road, London""",Tower Hamlets
3417,21.328781,"""114-114a Glengall Grove, London""",Tower Hamlets

In [ ]:
#might be worth starting to actually script it up into an executable?